# FRONTEND DOCKERFILE (DEV)
FROM node:18-alpine

WORKDIR /app

# Copy package.json first
COPY package*.json ./

# Install all deps
RUN npm install

# Copy rest of the frontend code
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Run Vite dev server and bind to container IP
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
